// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.1
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sha256_final (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ctx_final_in_data_address0,
        ctx_final_in_data_ce0,
        ctx_final_in_data_we0,
        ctx_final_in_data_d0,
        ctx_final_in_data_q0,
        ctx_final_in_data_address1,
        ctx_final_in_data_ce1,
        ctx_final_in_data_we1,
        ctx_final_in_data_d1,
        ctx_final_in_data_q1,
        ctx_final_datalen_read,
        ctx_final_bitlen_address0,
        ctx_final_bitlen_ce0,
        ctx_final_bitlen_we0,
        ctx_final_bitlen_d0,
        ctx_final_bitlen_q0,
        ctx_final_bitlen_address1,
        ctx_final_bitlen_ce1,
        ctx_final_bitlen_q1,
        ctx_final_state_address0,
        ctx_final_state_ce0,
        ctx_final_state_we0,
        ctx_final_state_d0,
        ctx_final_state_q0,
        ctx_final_state_address1,
        ctx_final_state_ce1,
        ctx_final_state_we1,
        ctx_final_state_d1,
        ctx_final_state_q1,
        final_hash_address1,
        final_hash_ce1,
        final_hash_we1,
        final_hash_d1
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] ctx_final_in_data_address0;
output   ctx_final_in_data_ce0;
output   ctx_final_in_data_we0;
output  [7:0] ctx_final_in_data_d0;
input  [7:0] ctx_final_in_data_q0;
output  [5:0] ctx_final_in_data_address1;
output   ctx_final_in_data_ce1;
output   ctx_final_in_data_we1;
output  [7:0] ctx_final_in_data_d1;
input  [7:0] ctx_final_in_data_q1;
input  [6:0] ctx_final_datalen_read;
output  [0:0] ctx_final_bitlen_address0;
output   ctx_final_bitlen_ce0;
output   ctx_final_bitlen_we0;
output  [31:0] ctx_final_bitlen_d0;
input  [31:0] ctx_final_bitlen_q0;
output  [0:0] ctx_final_bitlen_address1;
output   ctx_final_bitlen_ce1;
input  [31:0] ctx_final_bitlen_q1;
output  [2:0] ctx_final_state_address0;
output   ctx_final_state_ce0;
output   ctx_final_state_we0;
output  [31:0] ctx_final_state_d0;
input  [31:0] ctx_final_state_q0;
output  [2:0] ctx_final_state_address1;
output   ctx_final_state_ce1;
output   ctx_final_state_we1;
output  [31:0] ctx_final_state_d1;
input  [31:0] ctx_final_state_q1;
output  [5:0] final_hash_address1;
output   final_hash_ce1;
output   final_hash_we1;
output  [7:0] final_hash_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] ctx_final_in_data_address0;
reg ctx_final_in_data_ce0;
reg ctx_final_in_data_we0;
reg[7:0] ctx_final_in_data_d0;
reg[5:0] ctx_final_in_data_address1;
reg ctx_final_in_data_ce1;
reg ctx_final_in_data_we1;
reg[7:0] ctx_final_in_data_d1;
reg[0:0] ctx_final_bitlen_address0;
reg ctx_final_bitlen_ce0;
reg ctx_final_bitlen_we0;
reg[31:0] ctx_final_bitlen_d0;
reg ctx_final_bitlen_ce1;
reg[2:0] ctx_final_state_address0;
reg ctx_final_state_ce0;
reg ctx_final_state_we0;
reg[2:0] ctx_final_state_address1;
reg ctx_final_state_ce1;
reg ctx_final_state_we1;
reg[5:0] final_hash_address1;
reg final_hash_ce1;
reg final_hash_we1;
reg[7:0] final_hash_d1;
reg   [4:0] ap_CS_fsm = 5'b00000;
reg   [31:0] reg_479;
reg   [31:0] reg_483;
wire   [0:0] tmp_s_fu_502_p2;
reg   [0:0] tmp_s_reg_877;
wire   [6:0] tmp_fu_508_p2;
reg   [6:0] tmp_reg_881;
wire   [5:0] tmp17_fu_518_p2;
reg   [5:0] tmp17_reg_886;
wire   [5:0] tmp_51_fu_524_p1;
reg   [5:0] tmp_51_reg_891;
wire   [5:0] tmp1_fu_528_p2;
reg   [5:0] tmp1_reg_897;
wire   [0:0] tmp2_fu_534_p2;
reg   [0:0] tmp2_reg_902;
wire   [5:0] indvar_next_fu_559_p2;
wire   [5:0] j_1_fu_576_p2;
wire   [0:0] ctx_final_bitlen_addr_gep_fu_158_p3;
reg   [0:0] ctx_final_bitlen_addr_reg_923;
wire   [0:0] exitcond_fu_570_p2;
reg   [0:0] exitcond1_reg_943;
wire   [5:0] tmp_53_fu_582_p1;
reg   [5:0] tmp_53_reg_928;
wire   [6:0] tmp1_cast_fu_585_p1;
reg   [6:0] tmp1_cast_reg_933;
wire   [5:0] tmp4_fu_594_p2;
reg   [5:0] tmp4_reg_938;
wire   [0:0] exitcond1_fu_613_p2;
wire   [5:0] indvar_next1_fu_618_p2;
reg   [31:0] ctx_final_bitlen_load_reg_952;
wire   [31:0] tmp_1_cast_fu_631_p1;
reg   [31:0] tmp_1_cast_reg_958;
wire   [0:0] tmp_2_fu_641_p2;
reg   [0:0] tmp_2_reg_963;
wire   [0:0] ctx_final_bitlen_addr_1_gep_fu_179_p3;
reg   [0:0] ctx_final_bitlen_addr_1_reg_967;
reg   [31:0] ctx_final_bitlen_load_1_reg_972;
wire   [31:0] tmp_3_fu_646_p2;
reg   [31:0] tmp_3_reg_977;
wire   [31:0] tmp_4_fu_651_p2;
reg   [31:0] tmp_4_reg_982;
wire   [7:0] tmp_54_fu_655_p1;
reg   [7:0] tmp_54_reg_987;
reg   [7:0] tmp_7_reg_992;
reg   [7:0] tmp_9_reg_997;
reg   [7:0] tmp_8_reg_1002;
wire   [7:0] tmp_55_fu_689_p1;
reg   [7:0] tmp_55_reg_1012;
reg   [7:0] tmp_11_reg_1017;
reg   [7:0] tmp_12_reg_1022;
reg   [7:0] tmp_13_reg_1027;
wire   [2:0] ctx_final_state_addr_gep_fu_275_p3;
reg   [2:0] ctx_final_state_addr_reg_1032;
wire    grp_sha256_transform_fu_463_ap_done;
wire   [2:0] ctx_final_state_addr_1_gep_fu_283_p3;
reg   [2:0] ctx_final_state_addr_1_reg_1037;
wire   [2:0] ctx_final_state_addr_2_gep_fu_291_p3;
reg   [2:0] ctx_final_state_addr_2_reg_1042;
wire   [2:0] ctx_final_state_addr_3_gep_fu_299_p3;
reg   [2:0] ctx_final_state_addr_3_reg_1047;
wire   [2:0] ctx_final_state_addr_4_gep_fu_307_p3;
reg   [2:0] ctx_final_state_addr_4_reg_1052;
wire   [2:0] ctx_final_state_addr_5_gep_fu_315_p3;
reg   [2:0] ctx_final_state_addr_5_reg_1057;
wire   [2:0] ctx_final_state_addr_6_gep_fu_323_p3;
reg   [2:0] ctx_final_state_addr_6_reg_1062;
wire   [2:0] ctx_final_state_addr_7_gep_fu_331_p3;
reg   [2:0] ctx_final_state_addr_7_reg_1067;
wire   [3:0] i_2_cast9_fu_723_p1;
reg   [3:0] i_2_cast9_reg_1072;
wire   [4:0] i_2_cast8_fu_727_p1;
reg   [4:0] i_2_cast8_reg_1077;
wire   [31:0] i_2_cast_fu_731_p1;
reg   [31:0] i_2_cast_reg_1082;
wire   [2:0] i_3_fu_741_p2;
reg   [2:0] i_3_reg_1090;
wire   [31:0] tmp_20_cast_fu_765_p1;
reg   [31:0] tmp_20_cast_reg_1095;
wire   [7:0] tmp_57_fu_770_p1;
reg   [7:0] tmp_57_reg_1101;
wire   [7:0] tmp_58_fu_774_p1;
reg   [7:0] tmp_58_reg_1106;
wire   [7:0] tmp_59_fu_783_p1;
reg   [7:0] tmp_59_reg_1111;
wire   [7:0] tmp_60_fu_787_p1;
reg   [7:0] tmp_60_reg_1116;
wire   [7:0] tmp_61_fu_804_p1;
reg   [7:0] tmp_61_reg_1121;
wire   [7:0] tmp_62_fu_808_p1;
reg   [7:0] tmp_62_reg_1126;
wire   [2:0] grp_fu_473_p2;
reg   [2:0] sum6_reg_1131;
wire   [7:0] tmp_63_fu_821_p1;
reg   [7:0] tmp_63_reg_1136;
wire   [7:0] tmp_64_fu_825_p1;
reg   [7:0] tmp_64_reg_1141;
wire    grp_sha256_transform_fu_463_ap_start;
wire    grp_sha256_transform_fu_463_ap_idle;
wire    grp_sha256_transform_fu_463_ap_ready;
wire   [2:0] grp_sha256_transform_fu_463_ctx_transform_state_address0;
wire    grp_sha256_transform_fu_463_ctx_transform_state_ce0;
wire    grp_sha256_transform_fu_463_ctx_transform_state_we0;
wire   [31:0] grp_sha256_transform_fu_463_ctx_transform_state_d0;
wire   [31:0] grp_sha256_transform_fu_463_ctx_transform_state_q0;
wire   [2:0] grp_sha256_transform_fu_463_ctx_transform_state_address1;
wire    grp_sha256_transform_fu_463_ctx_transform_state_ce1;
wire    grp_sha256_transform_fu_463_ctx_transform_state_we1;
wire   [31:0] grp_sha256_transform_fu_463_ctx_transform_state_d1;
wire   [31:0] grp_sha256_transform_fu_463_ctx_transform_state_q1;
wire   [5:0] grp_sha256_transform_fu_463_data_transform_address0;
wire    grp_sha256_transform_fu_463_data_transform_ce0;
wire   [7:0] grp_sha256_transform_fu_463_data_transform_q0;
wire   [5:0] grp_sha256_transform_fu_463_data_transform_address1;
wire    grp_sha256_transform_fu_463_data_transform_ce1;
wire   [7:0] grp_sha256_transform_fu_463_data_transform_q1;
reg   [5:0] indvar_reg_417;
wire   [0:0] exitcond2_fu_554_p2;
reg   [5:0] j_reg_428;
reg   [5:0] indvar9_reg_439;
reg   [2:0] i_2_reg_450;
reg    grp_sha256_transform_fu_463_ap_start_ap_start_reg = 1'b0;
wire   [31:0] ctx_final_datalen_read_cast2_fu_497_p1;
wire   [31:0] i_1_cast_fu_549_p1;
wire   [31:0] j_cast_fu_565_p1;
wire   [31:0] i_cast_fu_608_p1;
wire   [31:0] sum2_cast_fu_778_p1;
wire   [31:0] sum4_cast_fu_799_p1;
wire   [31:0] sum6_cast_fu_816_p1;
wire   [31:0] sum8_cast_fu_836_p1;
wire   [31:0] sum_cast_fu_846_p1;
wire   [31:0] sum1_cast_fu_859_p1;
wire   [31:0] sum3_cast_fu_867_p1;
wire   [0:0] exitcond3_fu_735_p2;
reg   [31:0] grp_fu_487_p1;
wire   [5:0] tmp_52_fu_514_p1;
wire   [6:0] indvar_cast_fu_540_p1;
wire   [6:0] i_1_fu_544_p2;
wire   [5:0] tmp3_fu_588_p3;
wire   [6:0] indvar9_cast_fu_599_p1;
wire   [6:0] i_fu_603_p2;
wire   [8:0] tmp_1_fu_624_p3;
wire   [31:0] not_fu_635_p2;
wire   [1:0] tmp_56_fu_747_p1;
wire   [4:0] tmp_15_fu_751_p3;
wire   [4:0] tmp_16_fu_759_p2;
wire   [31:0] grp_fu_487_p2;
wire   [31:0] grp_fu_492_p2;
wire   [3:0] sum1_fu_791_p3;
wire   [3:0] sum6_cast_fu_816_p0;
wire   [4:0] sum4_fu_829_p3;
wire   [4:0] sum_fu_841_p2;
wire   [4:0] sum5_fu_851_p3;
wire   [4:0] sum3_cast_fu_867_p0;
reg   [4:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 5'b00000;
parameter    ap_ST_st2_fsm_1 = 5'b1;
parameter    ap_ST_st3_fsm_2 = 5'b10;
parameter    ap_ST_st4_fsm_3 = 5'b11;
parameter    ap_ST_st5_fsm_4 = 5'b100;
parameter    ap_ST_st6_fsm_5 = 5'b101;
parameter    ap_ST_st7_fsm_6 = 5'b110;
parameter    ap_ST_st8_fsm_7 = 5'b111;
parameter    ap_ST_st9_fsm_8 = 5'b1000;
parameter    ap_ST_st10_fsm_9 = 5'b1001;
parameter    ap_ST_st11_fsm_10 = 5'b1010;
parameter    ap_ST_st12_fsm_11 = 5'b1011;
parameter    ap_ST_st13_fsm_12 = 5'b1100;
parameter    ap_ST_st14_fsm_13 = 5'b1101;
parameter    ap_ST_st15_fsm_14 = 5'b1110;
parameter    ap_ST_st16_fsm_15 = 5'b1111;
parameter    ap_ST_st17_fsm_16 = 5'b10000;
parameter    ap_ST_st18_fsm_17 = 5'b10001;
parameter    ap_ST_st19_fsm_18 = 5'b10010;
parameter    ap_ST_st20_fsm_19 = 5'b10011;
parameter    ap_ST_st21_fsm_20 = 5'b10100;
parameter    ap_ST_st22_fsm_21 = 5'b10101;
parameter    ap_ST_st23_fsm_22 = 5'b10110;
parameter    ap_ST_st24_fsm_23 = 5'b10111;
parameter    ap_ST_st25_fsm_24 = 5'b11000;
parameter    ap_ST_st26_fsm_25 = 5'b11001;
parameter    ap_ST_st27_fsm_26 = 5'b11010;
parameter    ap_ST_st28_fsm_27 = 5'b11011;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_3E = 32'b111110;
parameter    ap_const_lv32_3D = 32'b111101;
parameter    ap_const_lv32_3C = 32'b111100;
parameter    ap_const_lv32_3B = 32'b111011;
parameter    ap_const_lv32_3A = 32'b111010;
parameter    ap_const_lv32_39 = 32'b111001;
parameter    ap_const_lv32_38 = 32'b111000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv8_80 = 8'b10000000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv7_38 = 7'b111000;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv6_3F = 6'b111111;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv6_38 = 6'b111000;
parameter    ap_const_lv6_37 = 6'b110111;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv5_18 = 5'b11000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv5_14 = 5'b10100;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_true = 1'b1;


sha256_transform grp_sha256_transform_fu_463(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_sha256_transform_fu_463_ap_start ),
    .ap_done( grp_sha256_transform_fu_463_ap_done ),
    .ap_idle( grp_sha256_transform_fu_463_ap_idle ),
    .ap_ready( grp_sha256_transform_fu_463_ap_ready ),
    .ctx_transform_state_address0( grp_sha256_transform_fu_463_ctx_transform_state_address0 ),
    .ctx_transform_state_ce0( grp_sha256_transform_fu_463_ctx_transform_state_ce0 ),
    .ctx_transform_state_we0( grp_sha256_transform_fu_463_ctx_transform_state_we0 ),
    .ctx_transform_state_d0( grp_sha256_transform_fu_463_ctx_transform_state_d0 ),
    .ctx_transform_state_q0( grp_sha256_transform_fu_463_ctx_transform_state_q0 ),
    .ctx_transform_state_address1( grp_sha256_transform_fu_463_ctx_transform_state_address1 ),
    .ctx_transform_state_ce1( grp_sha256_transform_fu_463_ctx_transform_state_ce1 ),
    .ctx_transform_state_we1( grp_sha256_transform_fu_463_ctx_transform_state_we1 ),
    .ctx_transform_state_d1( grp_sha256_transform_fu_463_ctx_transform_state_d1 ),
    .ctx_transform_state_q1( grp_sha256_transform_fu_463_ctx_transform_state_q1 ),
    .data_transform_address0( grp_sha256_transform_fu_463_data_transform_address0 ),
    .data_transform_ce0( grp_sha256_transform_fu_463_data_transform_ce0 ),
    .data_transform_q0( grp_sha256_transform_fu_463_data_transform_q0 ),
    .data_transform_address1( grp_sha256_transform_fu_463_data_transform_address1 ),
    .data_transform_ce1( grp_sha256_transform_fu_463_data_transform_ce1 ),
    .data_transform_q1( grp_sha256_transform_fu_463_data_transform_q1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// grp_sha256_transform_fu_463_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_sha256_transform_fu_463_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_sha256_transform_fu_463_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_554_p2)) | (ap_ST_st16_fsm_15 == ap_CS_fsm))) begin
            grp_sha256_transform_fu_463_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_sha256_transform_fu_463_ap_ready)) begin
            grp_sha256_transform_fu_463_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        ctx_final_bitlen_load_1_reg_972 <= ctx_final_bitlen_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st7_fsm_6 == ap_CS_fsm)) begin
        ctx_final_bitlen_load_reg_952 <= ctx_final_bitlen_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        exitcond1_reg_943 <= exitcond1_fu_613_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st18_fsm_17 == ap_CS_fsm)) begin
        i_2_cast8_reg_1077[0] <= i_2_cast8_fu_727_p1[0];
        i_2_cast8_reg_1077[1] <= i_2_cast8_fu_727_p1[1];
        i_2_cast8_reg_1077[2] <= i_2_cast8_fu_727_p1[2];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st18_fsm_17 == ap_CS_fsm)) begin
        i_2_cast9_reg_1072[0] <= i_2_cast9_fu_723_p1[0];
        i_2_cast9_reg_1072[1] <= i_2_cast9_fu_723_p1[1];
        i_2_cast9_reg_1072[2] <= i_2_cast9_fu_723_p1[2];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st18_fsm_17 == ap_CS_fsm)) begin
        i_2_cast_reg_1082[0] <= i_2_cast_fu_731_p1[0];
        i_2_cast_reg_1082[1] <= i_2_cast_fu_731_p1[1];
        i_2_cast_reg_1082[2] <= i_2_cast_fu_731_p1[2];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        i_2_reg_450 <= i_3_reg_1090;
    end else if (((ap_ST_st17_fsm_16 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_sha256_transform_fu_463_ap_done))) begin
        i_2_reg_450 <= ap_const_lv3_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st18_fsm_17 == ap_CS_fsm)) begin
        i_3_reg_1090 <= i_3_fu_741_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        indvar9_reg_439 <= ap_const_lv6_0;
    end else if (((ap_ST_st6_fsm_5 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_613_p2))) begin
        indvar9_reg_439 <= indvar_next1_fu_618_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0) & (tmp_s_fu_502_p2 == ap_const_lv1_0))) begin
        indvar_reg_417 <= ap_const_lv6_0;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_554_p2))) begin
        indvar_reg_417 <= indvar_next_fu_559_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & (tmp_s_reg_877 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond_fu_570_p2))) begin
        j_reg_428 <= j_1_fu_576_p2;
    end else if ((~(ap_const_logic_0 == grp_sha256_transform_fu_463_ap_done) & (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        j_reg_428 <= ap_const_lv6_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st19_fsm_18 == ap_CS_fsm) | (ap_ST_st20_fsm_19 == ap_CS_fsm) | (ap_ST_st21_fsm_20 == ap_CS_fsm) | (ap_ST_st22_fsm_21 == ap_CS_fsm) | (ap_ST_st23_fsm_22 == ap_CS_fsm))) begin
        reg_479 <= ctx_final_state_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st21_fsm_20 == ap_CS_fsm) | (ap_ST_st22_fsm_21 == ap_CS_fsm) | (ap_ST_st23_fsm_22 == ap_CS_fsm))) begin
        reg_483 <= ctx_final_state_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        sum6_reg_1131 <= grp_fu_473_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0) & (tmp_s_fu_502_p2 == ap_const_lv1_0))) begin
        tmp17_reg_886 <= tmp17_fu_518_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        tmp1_cast_reg_933[0] <= tmp1_cast_fu_585_p1[0];
        tmp1_cast_reg_933[1] <= tmp1_cast_fu_585_p1[1];
        tmp1_cast_reg_933[2] <= tmp1_cast_fu_585_p1[2];
        tmp1_cast_reg_933[3] <= tmp1_cast_fu_585_p1[3];
        tmp1_cast_reg_933[4] <= tmp1_cast_fu_585_p1[4];
        tmp1_cast_reg_933[5] <= tmp1_cast_fu_585_p1[5];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0) & ~(tmp_s_fu_502_p2 == ap_const_lv1_0))) begin
        tmp1_reg_897 <= tmp1_fu_528_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0) & ~(tmp_s_fu_502_p2 == ap_const_lv1_0))) begin
        tmp2_reg_902 <= tmp2_fu_534_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        tmp4_reg_938 <= tmp4_fu_594_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        tmp_11_reg_1017 <= {{ctx_final_bitlen_q1[ap_const_lv32_F : ap_const_lv32_8]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        tmp_12_reg_1022 <= {{ctx_final_bitlen_q1[ap_const_lv32_17 : ap_const_lv32_10]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        tmp_13_reg_1027 <= {{ctx_final_bitlen_q1[ap_const_lv32_1F : ap_const_lv32_18]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        tmp_1_cast_reg_958[3] <= tmp_1_cast_fu_631_p1[3];
        tmp_1_cast_reg_958[4] <= tmp_1_cast_fu_631_p1[4];
        tmp_1_cast_reg_958[5] <= tmp_1_cast_fu_631_p1[5];
        tmp_1_cast_reg_958[6] <= tmp_1_cast_fu_631_p1[6];
        tmp_1_cast_reg_958[7] <= tmp_1_cast_fu_631_p1[7];
        tmp_1_cast_reg_958[8] <= tmp_1_cast_fu_631_p1[8];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st20_fsm_19 == ap_CS_fsm)) begin
        tmp_20_cast_reg_1095[3] <= tmp_20_cast_fu_765_p1[3];
        tmp_20_cast_reg_1095[4] <= tmp_20_cast_fu_765_p1[4];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        tmp_2_reg_963 <= tmp_2_fu_641_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st10_fsm_9 == ap_CS_fsm)) begin
        tmp_3_reg_977 <= tmp_3_fu_646_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        tmp_4_reg_982 <= tmp_4_fu_651_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0) & ~(tmp_s_fu_502_p2 == ap_const_lv1_0))) begin
        tmp_51_reg_891 <= tmp_51_fu_524_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & (((tmp_s_reg_877 == ap_const_lv1_0) & ~(ap_const_lv1_0 == exitcond_fu_570_p2)) | (~(tmp_s_reg_877 == ap_const_lv1_0) & ~(ap_const_lv1_0 == exitcond1_reg_943))))) begin
        tmp_53_reg_928 <= tmp_53_fu_582_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        tmp_54_reg_987 <= tmp_54_fu_655_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        tmp_55_reg_1012 <= tmp_55_fu_689_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st20_fsm_19 == ap_CS_fsm)) begin
        tmp_57_reg_1101 <= tmp_57_fu_770_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st21_fsm_20 == ap_CS_fsm)) begin
        tmp_58_reg_1106 <= tmp_58_fu_774_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st22_fsm_21 == ap_CS_fsm)) begin
        tmp_59_reg_1111 <= tmp_59_fu_783_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st22_fsm_21 == ap_CS_fsm)) begin
        tmp_60_reg_1116 <= tmp_60_fu_787_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st23_fsm_22 == ap_CS_fsm)) begin
        tmp_61_reg_1121 <= tmp_61_fu_804_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st23_fsm_22 == ap_CS_fsm)) begin
        tmp_62_reg_1126 <= tmp_62_fu_808_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        tmp_63_reg_1136 <= tmp_63_fu_821_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        tmp_64_reg_1141 <= tmp_64_fu_825_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        tmp_7_reg_992 <= {{tmp_4_fu_651_p2[ap_const_lv32_F : ap_const_lv32_8]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        tmp_8_reg_1002 <= {{tmp_4_fu_651_p2[ap_const_lv32_1F : ap_const_lv32_18]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        tmp_9_reg_997 <= {{tmp_4_fu_651_p2[ap_const_lv32_17 : ap_const_lv32_10]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0) & (tmp_s_fu_502_p2 == ap_const_lv1_0))) begin
        tmp_reg_881 <= tmp_fu_508_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        tmp_s_reg_877 <= tmp_s_fu_502_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_CS_fsm or exitcond3_fu_735_p2)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm)) | ((ap_ST_st18_fsm_17 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond3_fu_735_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond3_fu_735_p2)
begin
    if (((ap_ST_st18_fsm_17 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond3_fu_735_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ctx_final_bitlen_address0 assign process. ///
always @ (ap_CS_fsm or ctx_final_bitlen_addr_reg_923 or ctx_final_bitlen_addr_1_reg_967)
begin
    if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        ctx_final_bitlen_address0 = ctx_final_bitlen_addr_reg_923;
    end else if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        ctx_final_bitlen_address0 = ctx_final_bitlen_addr_1_reg_967;
    end else if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        ctx_final_bitlen_address0 = ap_const_lv32_1;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        ctx_final_bitlen_address0 = ap_const_lv32_0;
    end else begin
        ctx_final_bitlen_address0 = ctx_final_bitlen_addr_1_reg_967;
    end
end

/// ctx_final_bitlen_ce0 assign process. ///
always @ (ap_CS_fsm or tmp_s_reg_877 or exitcond_fu_570_p2 or exitcond1_reg_943 or tmp_2_fu_641_p2 or tmp_2_reg_963)
begin
    if ((((ap_ST_st4_fsm_3 == ap_CS_fsm) & (((tmp_s_reg_877 == ap_const_lv1_0) & ~(ap_const_lv1_0 == exitcond_fu_570_p2)) | (~(tmp_s_reg_877 == ap_const_lv1_0) & ~(ap_const_lv1_0 == exitcond1_reg_943)))) | ((ap_ST_st8_fsm_7 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_fu_641_p2)) | (ap_ST_st12_fsm_11 == ap_CS_fsm) | ((ap_ST_st11_fsm_10 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_reg_963)))) begin
        ctx_final_bitlen_ce0 = ap_const_logic_1;
    end else begin
        ctx_final_bitlen_ce0 = ap_const_logic_0;
    end
end

/// ctx_final_bitlen_ce1 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        ctx_final_bitlen_ce1 = ap_const_logic_1;
    end else begin
        ctx_final_bitlen_ce1 = ap_const_logic_0;
    end
end

/// ctx_final_bitlen_d0 assign process. ///
always @ (ap_CS_fsm or tmp_3_reg_977 or tmp_4_reg_982)
begin
    if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        ctx_final_bitlen_d0 = tmp_4_reg_982;
    end else if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        ctx_final_bitlen_d0 = tmp_3_reg_977;
    end else begin
        ctx_final_bitlen_d0 = tmp_4_reg_982;
    end
end

/// ctx_final_bitlen_we0 assign process. ///
always @ (ap_CS_fsm or tmp_2_reg_963)
begin
    if (((ap_ST_st12_fsm_11 == ap_CS_fsm) | ((ap_ST_st11_fsm_10 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_2_reg_963)))) begin
        ctx_final_bitlen_we0 = ap_const_logic_1;
    end else begin
        ctx_final_bitlen_we0 = ap_const_logic_0;
    end
end

/// ctx_final_in_data_address0 assign process. ///
always @ (ap_CS_fsm or grp_sha256_transform_fu_463_data_transform_address0 or ctx_final_datalen_read_cast2_fu_497_p1 or i_1_cast_fu_549_p1 or j_cast_fu_565_p1 or i_cast_fu_608_p1)
begin
    if ((ap_ST_st15_fsm_14 == ap_CS_fsm)) begin
        ctx_final_in_data_address0 = ap_const_lv32_39;
    end else if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        ctx_final_in_data_address0 = ap_const_lv32_3B;
    end else if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        ctx_final_in_data_address0 = ap_const_lv32_3D;
    end else if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        ctx_final_in_data_address0 = ap_const_lv32_3F;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        ctx_final_in_data_address0 = i_cast_fu_608_p1;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        ctx_final_in_data_address0 = j_cast_fu_565_p1;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        ctx_final_in_data_address0 = i_1_cast_fu_549_p1;
    end else if ((ap_ST_st1_fsm_0 == ap_CS_fsm)) begin
        ctx_final_in_data_address0 = ctx_final_datalen_read_cast2_fu_497_p1;
    end else if (((ap_ST_st17_fsm_16 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        ctx_final_in_data_address0 = grp_sha256_transform_fu_463_data_transform_address0;
    end else begin
        ctx_final_in_data_address0 = ap_const_lv32_39;
    end
end

/// ctx_final_in_data_address1 assign process. ///
always @ (ap_CS_fsm or grp_sha256_transform_fu_463_data_transform_address1)
begin
    if ((ap_ST_st15_fsm_14 == ap_CS_fsm)) begin
        ctx_final_in_data_address1 = ap_const_lv32_38;
    end else if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        ctx_final_in_data_address1 = ap_const_lv32_3A;
    end else if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        ctx_final_in_data_address1 = ap_const_lv32_3C;
    end else if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        ctx_final_in_data_address1 = ap_const_lv32_3E;
    end else if (((ap_ST_st17_fsm_16 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        ctx_final_in_data_address1 = grp_sha256_transform_fu_463_data_transform_address1;
    end else begin
        ctx_final_in_data_address1 = ap_const_lv32_38;
    end
end

/// ctx_final_in_data_ce0 assign process. ///
always @ (ap_start or ap_CS_fsm or tmp_s_reg_877 or exitcond_fu_570_p2 or exitcond1_fu_613_p2 or grp_sha256_transform_fu_463_data_transform_ce0 or exitcond2_fu_554_p2)
begin
    if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0)) | (ap_ST_st12_fsm_11 == ap_CS_fsm) | (ap_ST_st13_fsm_12 == ap_CS_fsm) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_554_p2)) | ((ap_ST_st4_fsm_3 == ap_CS_fsm) & (tmp_s_reg_877 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond_fu_570_p2)) | ((ap_ST_st6_fsm_5 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_613_p2)) | (ap_ST_st14_fsm_13 == ap_CS_fsm) | (ap_ST_st15_fsm_14 == ap_CS_fsm))) begin
        ctx_final_in_data_ce0 = ap_const_logic_1;
    end else if (((ap_ST_st17_fsm_16 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        ctx_final_in_data_ce0 = grp_sha256_transform_fu_463_data_transform_ce0;
    end else begin
        ctx_final_in_data_ce0 = ap_const_logic_0;
    end
end

/// ctx_final_in_data_ce1 assign process. ///
always @ (ap_CS_fsm or grp_sha256_transform_fu_463_data_transform_ce1)
begin
    if (((ap_ST_st12_fsm_11 == ap_CS_fsm) | (ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st14_fsm_13 == ap_CS_fsm) | (ap_ST_st15_fsm_14 == ap_CS_fsm))) begin
        ctx_final_in_data_ce1 = ap_const_logic_1;
    end else if (((ap_ST_st17_fsm_16 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        ctx_final_in_data_ce1 = grp_sha256_transform_fu_463_data_transform_ce1;
    end else begin
        ctx_final_in_data_ce1 = ap_const_logic_0;
    end
end

/// ctx_final_in_data_d0 assign process. ///
always @ (ap_CS_fsm or tmp_54_reg_987 or tmp_9_reg_997 or tmp_55_reg_1012 or tmp_12_reg_1022)
begin
    if ((ap_ST_st15_fsm_14 == ap_CS_fsm)) begin
        ctx_final_in_data_d0 = tmp_12_reg_1022;
    end else if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        ctx_final_in_data_d0 = tmp_55_reg_1012;
    end else if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        ctx_final_in_data_d0 = tmp_9_reg_997;
    end else if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        ctx_final_in_data_d0 = tmp_54_reg_987;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st4_fsm_3 == ap_CS_fsm) | (ap_ST_st6_fsm_5 == ap_CS_fsm))) begin
        ctx_final_in_data_d0 = ap_const_lv8_0;
    end else if ((ap_ST_st1_fsm_0 == ap_CS_fsm)) begin
        ctx_final_in_data_d0 = ap_const_lv8_80;
    end else begin
        ctx_final_in_data_d0 = ap_const_lv8_0;
    end
end

/// ctx_final_in_data_d1 assign process. ///
always @ (ap_CS_fsm or tmp_7_reg_992 or tmp_8_reg_1002 or tmp_11_reg_1017 or tmp_13_reg_1027)
begin
    if ((ap_ST_st15_fsm_14 == ap_CS_fsm)) begin
        ctx_final_in_data_d1 = tmp_13_reg_1027;
    end else if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        ctx_final_in_data_d1 = tmp_11_reg_1017;
    end else if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        ctx_final_in_data_d1 = tmp_8_reg_1002;
    end else if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        ctx_final_in_data_d1 = tmp_7_reg_992;
    end else begin
        ctx_final_in_data_d1 = tmp_13_reg_1027;
    end
end

/// ctx_final_in_data_we0 assign process. ///
always @ (ap_start or ap_CS_fsm or tmp_s_reg_877 or exitcond_fu_570_p2 or exitcond1_fu_613_p2 or exitcond2_fu_554_p2)
begin
    if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0)) | (ap_ST_st12_fsm_11 == ap_CS_fsm) | (ap_ST_st13_fsm_12 == ap_CS_fsm) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_554_p2)) | ((ap_ST_st4_fsm_3 == ap_CS_fsm) & (tmp_s_reg_877 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond_fu_570_p2)) | ((ap_ST_st6_fsm_5 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_613_p2)) | (ap_ST_st14_fsm_13 == ap_CS_fsm) | (ap_ST_st15_fsm_14 == ap_CS_fsm))) begin
        ctx_final_in_data_we0 = ap_const_logic_1;
    end else begin
        ctx_final_in_data_we0 = ap_const_logic_0;
    end
end

/// ctx_final_in_data_we1 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st12_fsm_11 == ap_CS_fsm) | (ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st14_fsm_13 == ap_CS_fsm) | (ap_ST_st15_fsm_14 == ap_CS_fsm))) begin
        ctx_final_in_data_we1 = ap_const_logic_1;
    end else begin
        ctx_final_in_data_we1 = ap_const_logic_0;
    end
end

/// ctx_final_state_address0 assign process. ///
always @ (ap_CS_fsm or ctx_final_state_addr_reg_1032 or ctx_final_state_addr_1_reg_1037 or ctx_final_state_addr_2_reg_1042 or ctx_final_state_addr_4_reg_1052 or ctx_final_state_addr_6_reg_1062 or grp_sha256_transform_fu_463_ctx_transform_state_address0)
begin
    if ((ap_ST_st22_fsm_21 == ap_CS_fsm)) begin
        ctx_final_state_address0 = ctx_final_state_addr_6_reg_1062;
    end else if ((ap_ST_st21_fsm_20 == ap_CS_fsm)) begin
        ctx_final_state_address0 = ctx_final_state_addr_4_reg_1052;
    end else if ((ap_ST_st20_fsm_19 == ap_CS_fsm)) begin
        ctx_final_state_address0 = ctx_final_state_addr_2_reg_1042;
    end else if ((ap_ST_st19_fsm_18 == ap_CS_fsm)) begin
        ctx_final_state_address0 = ctx_final_state_addr_1_reg_1037;
    end else if ((ap_ST_st18_fsm_17 == ap_CS_fsm)) begin
        ctx_final_state_address0 = ctx_final_state_addr_reg_1032;
    end else if (((ap_ST_st17_fsm_16 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        ctx_final_state_address0 = grp_sha256_transform_fu_463_ctx_transform_state_address0;
    end else begin
        ctx_final_state_address0 = grp_sha256_transform_fu_463_ctx_transform_state_address0;
    end
end

/// ctx_final_state_address1 assign process. ///
always @ (ap_CS_fsm or ctx_final_state_addr_3_reg_1047 or ctx_final_state_addr_5_reg_1057 or ctx_final_state_addr_7_reg_1067 or grp_sha256_transform_fu_463_ctx_transform_state_address1)
begin
    if ((ap_ST_st22_fsm_21 == ap_CS_fsm)) begin
        ctx_final_state_address1 = ctx_final_state_addr_7_reg_1067;
    end else if ((ap_ST_st21_fsm_20 == ap_CS_fsm)) begin
        ctx_final_state_address1 = ctx_final_state_addr_5_reg_1057;
    end else if ((ap_ST_st20_fsm_19 == ap_CS_fsm)) begin
        ctx_final_state_address1 = ctx_final_state_addr_3_reg_1047;
    end else if (((ap_ST_st17_fsm_16 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        ctx_final_state_address1 = grp_sha256_transform_fu_463_ctx_transform_state_address1;
    end else begin
        ctx_final_state_address1 = grp_sha256_transform_fu_463_ctx_transform_state_address1;
    end
end

/// ctx_final_state_ce0 assign process. ///
always @ (ap_CS_fsm or grp_sha256_transform_fu_463_ctx_transform_state_ce0 or exitcond3_fu_735_p2)
begin
    if (((ap_ST_st19_fsm_18 == ap_CS_fsm) | (ap_ST_st20_fsm_19 == ap_CS_fsm) | (ap_ST_st21_fsm_20 == ap_CS_fsm) | (ap_ST_st22_fsm_21 == ap_CS_fsm) | ((ap_ST_st18_fsm_17 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_735_p2)))) begin
        ctx_final_state_ce0 = ap_const_logic_1;
    end else if (((ap_ST_st17_fsm_16 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        ctx_final_state_ce0 = grp_sha256_transform_fu_463_ctx_transform_state_ce0;
    end else begin
        ctx_final_state_ce0 = ap_const_logic_0;
    end
end

/// ctx_final_state_ce1 assign process. ///
always @ (ap_CS_fsm or grp_sha256_transform_fu_463_ctx_transform_state_ce1)
begin
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) | (ap_ST_st21_fsm_20 == ap_CS_fsm) | (ap_ST_st22_fsm_21 == ap_CS_fsm))) begin
        ctx_final_state_ce1 = ap_const_logic_1;
    end else if (((ap_ST_st17_fsm_16 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        ctx_final_state_ce1 = grp_sha256_transform_fu_463_ctx_transform_state_ce1;
    end else begin
        ctx_final_state_ce1 = ap_const_logic_0;
    end
end

/// ctx_final_state_we0 assign process. ///
always @ (ap_CS_fsm or grp_sha256_transform_fu_463_ctx_transform_state_we0)
begin
    if (((ap_ST_st17_fsm_16 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        ctx_final_state_we0 = grp_sha256_transform_fu_463_ctx_transform_state_we0;
    end else begin
        ctx_final_state_we0 = ap_const_logic_0;
    end
end

/// ctx_final_state_we1 assign process. ///
always @ (ap_CS_fsm or grp_sha256_transform_fu_463_ctx_transform_state_we1)
begin
    if (((ap_ST_st17_fsm_16 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        ctx_final_state_we1 = grp_sha256_transform_fu_463_ctx_transform_state_we1;
    end else begin
        ctx_final_state_we1 = ap_const_logic_0;
    end
end

/// final_hash_address1 assign process. ///
always @ (ap_CS_fsm or i_2_cast_reg_1082 or sum2_cast_fu_778_p1 or sum4_cast_fu_799_p1 or sum6_cast_fu_816_p1 or sum8_cast_fu_836_p1 or sum_cast_fu_846_p1 or sum1_cast_fu_859_p1 or sum3_cast_fu_867_p1)
begin
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        final_hash_address1 = sum3_cast_fu_867_p1;
    end else if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        final_hash_address1 = sum1_cast_fu_859_p1;
    end else if ((ap_ST_st26_fsm_25 == ap_CS_fsm)) begin
        final_hash_address1 = sum_cast_fu_846_p1;
    end else if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        final_hash_address1 = sum8_cast_fu_836_p1;
    end else if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        final_hash_address1 = sum6_cast_fu_816_p1;
    end else if ((ap_ST_st23_fsm_22 == ap_CS_fsm)) begin
        final_hash_address1 = sum4_cast_fu_799_p1;
    end else if ((ap_ST_st22_fsm_21 == ap_CS_fsm)) begin
        final_hash_address1 = sum2_cast_fu_778_p1;
    end else if ((ap_ST_st21_fsm_20 == ap_CS_fsm)) begin
        final_hash_address1 = i_2_cast_reg_1082;
    end else begin
        final_hash_address1 = sum3_cast_fu_867_p1;
    end
end

/// final_hash_ce1 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st21_fsm_20 == ap_CS_fsm) | (ap_ST_st22_fsm_21 == ap_CS_fsm) | (ap_ST_st23_fsm_22 == ap_CS_fsm) | (ap_ST_st24_fsm_23 == ap_CS_fsm) | (ap_ST_st28_fsm_27 == ap_CS_fsm) | (ap_ST_st25_fsm_24 == ap_CS_fsm) | (ap_ST_st26_fsm_25 == ap_CS_fsm) | (ap_ST_st27_fsm_26 == ap_CS_fsm))) begin
        final_hash_ce1 = ap_const_logic_1;
    end else begin
        final_hash_ce1 = ap_const_logic_0;
    end
end

/// final_hash_d1 assign process. ///
always @ (ap_CS_fsm or tmp_57_reg_1101 or tmp_58_reg_1106 or tmp_59_reg_1111 or tmp_60_reg_1116 or tmp_61_reg_1121 or tmp_62_reg_1126 or tmp_63_reg_1136 or tmp_64_reg_1141)
begin
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        final_hash_d1 = tmp_64_reg_1141;
    end else if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        final_hash_d1 = tmp_63_reg_1136;
    end else if ((ap_ST_st26_fsm_25 == ap_CS_fsm)) begin
        final_hash_d1 = tmp_62_reg_1126;
    end else if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        final_hash_d1 = tmp_61_reg_1121;
    end else if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        final_hash_d1 = tmp_60_reg_1116;
    end else if ((ap_ST_st23_fsm_22 == ap_CS_fsm)) begin
        final_hash_d1 = tmp_59_reg_1111;
    end else if ((ap_ST_st22_fsm_21 == ap_CS_fsm)) begin
        final_hash_d1 = tmp_58_reg_1106;
    end else if ((ap_ST_st21_fsm_20 == ap_CS_fsm)) begin
        final_hash_d1 = tmp_57_reg_1101;
    end else begin
        final_hash_d1 = tmp_64_reg_1141;
    end
end

/// final_hash_we1 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st21_fsm_20 == ap_CS_fsm) | (ap_ST_st22_fsm_21 == ap_CS_fsm) | (ap_ST_st23_fsm_22 == ap_CS_fsm) | (ap_ST_st24_fsm_23 == ap_CS_fsm) | (ap_ST_st28_fsm_27 == ap_CS_fsm) | (ap_ST_st25_fsm_24 == ap_CS_fsm) | (ap_ST_st26_fsm_25 == ap_CS_fsm) | (ap_ST_st27_fsm_26 == ap_CS_fsm))) begin
        final_hash_we1 = ap_const_logic_1;
    end else begin
        final_hash_we1 = ap_const_logic_0;
    end
end

/// grp_fu_487_p1 assign process. ///
always @ (ap_CS_fsm or tmp_20_cast_fu_765_p1 or tmp_20_cast_reg_1095)
begin
    if (((ap_ST_st21_fsm_20 == ap_CS_fsm) | (ap_ST_st22_fsm_21 == ap_CS_fsm) | (ap_ST_st23_fsm_22 == ap_CS_fsm) | (ap_ST_st24_fsm_23 == ap_CS_fsm))) begin
        grp_fu_487_p1 = tmp_20_cast_reg_1095;
    end else if ((ap_ST_st20_fsm_19 == ap_CS_fsm)) begin
        grp_fu_487_p1 = tmp_20_cast_fu_765_p1;
    end else begin
        grp_fu_487_p1 = tmp_20_cast_reg_1095;
    end
end
always @ (ap_start or ap_CS_fsm or tmp_s_fu_502_p2 or tmp_s_reg_877 or exitcond_fu_570_p2 or exitcond1_fu_613_p2 or tmp_2_fu_641_p2 or grp_sha256_transform_fu_463_ap_done or exitcond2_fu_554_p2 or exitcond3_fu_735_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if ((~(ap_start == ap_const_logic_0) & (tmp_s_fu_502_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else if ((~(ap_start == ap_const_logic_0) & ~(tmp_s_fu_502_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if ((ap_const_lv1_0 == exitcond2_fu_554_p2)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st3_fsm_2 : 
            if (~(ap_const_logic_0 == grp_sha256_transform_fu_463_ap_done)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st4_fsm_3 : 
            if (((tmp_s_reg_877 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond_fu_570_p2))) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        ap_ST_st5_fsm_4 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
        ap_ST_st6_fsm_5 : 
            if ((ap_const_lv1_0 == exitcond1_fu_613_p2)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        ap_ST_st7_fsm_6 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
        ap_ST_st8_fsm_7 : 
            if ((ap_const_lv1_0 == tmp_2_fu_641_p2)) begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        ap_ST_st9_fsm_8 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
        ap_ST_st10_fsm_9 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
        ap_ST_st11_fsm_10 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
        ap_ST_st12_fsm_11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
        ap_ST_st13_fsm_12 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
        ap_ST_st14_fsm_13 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
        ap_ST_st15_fsm_14 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
        ap_ST_st16_fsm_15 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
        ap_ST_st17_fsm_16 : 
            if (~(ap_const_logic_0 == grp_sha256_transform_fu_463_ap_done)) begin
                ap_NS_fsm = ap_ST_st18_fsm_17;
            end else begin
                ap_NS_fsm = ap_ST_st17_fsm_16;
            end
        ap_ST_st18_fsm_17 : 
            if (~(ap_const_lv1_0 == exitcond3_fu_735_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st19_fsm_18;
            end
        ap_ST_st19_fsm_18 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
        ap_ST_st20_fsm_19 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
        ap_ST_st21_fsm_20 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
        ap_ST_st22_fsm_21 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
        ap_ST_st23_fsm_22 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
        ap_ST_st24_fsm_23 : 
            ap_NS_fsm = ap_ST_st25_fsm_24;
        ap_ST_st25_fsm_24 : 
            ap_NS_fsm = ap_ST_st26_fsm_25;
        ap_ST_st26_fsm_25 : 
            ap_NS_fsm = ap_ST_st27_fsm_26;
        ap_ST_st27_fsm_26 : 
            ap_NS_fsm = ap_ST_st28_fsm_27;
        ap_ST_st28_fsm_27 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end
assign ctx_final_bitlen_addr_1_gep_fu_179_p3 = ap_const_lv32_1;
assign ctx_final_bitlen_addr_gep_fu_158_p3 = ap_const_lv32_0;
assign ctx_final_bitlen_address1 = ap_const_lv32_1;
assign ctx_final_datalen_read_cast2_fu_497_p1 = $unsigned(ctx_final_datalen_read);
assign ctx_final_state_addr_1_gep_fu_283_p3 = ap_const_lv32_1;
assign ctx_final_state_addr_2_gep_fu_291_p3 = ap_const_lv32_2;
assign ctx_final_state_addr_3_gep_fu_299_p3 = ap_const_lv32_3;
assign ctx_final_state_addr_4_gep_fu_307_p3 = ap_const_lv32_4;
assign ctx_final_state_addr_5_gep_fu_315_p3 = ap_const_lv32_5;
assign ctx_final_state_addr_6_gep_fu_323_p3 = ap_const_lv32_6;
assign ctx_final_state_addr_7_gep_fu_331_p3 = ap_const_lv32_7;
assign ctx_final_state_addr_gep_fu_275_p3 = ap_const_lv32_0;
assign ctx_final_state_d0 = grp_sha256_transform_fu_463_ctx_transform_state_d0;
assign ctx_final_state_d1 = grp_sha256_transform_fu_463_ctx_transform_state_d1;
assign exitcond1_fu_613_p2 = (indvar9_reg_439 == tmp4_reg_938? 1'b1: 1'b0);
assign exitcond2_fu_554_p2 = (indvar_reg_417 == tmp17_reg_886? 1'b1: 1'b0);
assign exitcond3_fu_735_p2 = (i_2_reg_450 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond_fu_570_p2 = (j_reg_428 == ap_const_lv6_38? 1'b1: 1'b0);
assign grp_fu_473_p2 = (i_2_reg_450 ^ ap_const_lv3_4);
assign grp_fu_487_p2 = reg_479 >> grp_fu_487_p1;
assign grp_fu_492_p2 = reg_483 >> tmp_20_cast_reg_1095;
assign grp_sha256_transform_fu_463_ap_start = grp_sha256_transform_fu_463_ap_start_ap_start_reg;
assign grp_sha256_transform_fu_463_ctx_transform_state_q0 = ctx_final_state_q0;
assign grp_sha256_transform_fu_463_ctx_transform_state_q1 = ctx_final_state_q1;
assign grp_sha256_transform_fu_463_data_transform_q0 = ctx_final_in_data_q0;
assign grp_sha256_transform_fu_463_data_transform_q1 = ctx_final_in_data_q1;
assign i_1_cast_fu_549_p1 = $unsigned(i_1_fu_544_p2);
assign i_1_fu_544_p2 = (tmp_reg_881 + indvar_cast_fu_540_p1);
assign i_2_cast8_fu_727_p1 = $unsigned(i_2_reg_450);
assign i_2_cast9_fu_723_p1 = $unsigned(i_2_reg_450);
assign i_2_cast_fu_731_p1 = $unsigned(i_2_reg_450);
assign i_3_fu_741_p2 = (i_2_reg_450 + ap_const_lv3_1);
assign i_cast_fu_608_p1 = $unsigned(i_fu_603_p2);
assign i_fu_603_p2 = (tmp1_cast_reg_933 + indvar9_cast_fu_599_p1);
assign indvar9_cast_fu_599_p1 = $unsigned(indvar9_reg_439);
assign indvar_cast_fu_540_p1 = $unsigned(indvar_reg_417);
assign indvar_next1_fu_618_p2 = (indvar9_reg_439 + ap_const_lv6_1);
assign indvar_next_fu_559_p2 = (indvar_reg_417 + ap_const_lv6_1);
assign j_1_fu_576_p2 = (j_reg_428 + ap_const_lv6_1);
assign j_cast_fu_565_p1 = $unsigned(j_reg_428);
assign not_fu_635_p2 = (tmp_1_cast_fu_631_p1 ^ ap_const_lv32_FFFFFFFF);
assign sum1_cast_fu_859_p1 = $unsigned(sum5_fu_851_p3);
assign sum1_fu_791_p3 = {{ap_const_lv1_1}, {i_2_reg_450}};
assign sum2_cast_fu_778_p1 = $unsigned(grp_fu_473_p2);
assign sum3_cast_fu_867_p0 = $signed(sum6_reg_1131);
assign sum3_cast_fu_867_p1 = $unsigned(sum3_cast_fu_867_p0);
assign sum4_cast_fu_799_p1 = $unsigned(sum1_fu_791_p3);
assign sum4_fu_829_p3 = {{ap_const_lv1_1}, {i_2_cast9_reg_1072}};
assign sum5_fu_851_p3 = {{ap_const_lv2_3}, {i_2_reg_450}};
assign sum6_cast_fu_816_p0 = $signed(grp_fu_473_p2);
assign sum6_cast_fu_816_p1 = $unsigned(sum6_cast_fu_816_p0);
assign sum8_cast_fu_836_p1 = $unsigned(sum4_fu_829_p3);
assign sum_cast_fu_846_p1 = $unsigned(sum_fu_841_p2);
assign sum_fu_841_p2 = (i_2_cast8_reg_1077 + ap_const_lv5_14);
assign tmp17_fu_518_p2 = (tmp_52_fu_514_p1 ^ ap_const_lv6_3F);
assign tmp1_cast_fu_585_p1 = $unsigned(tmp1_reg_897);
assign tmp1_fu_528_p2 = (tmp_51_fu_524_p1 + ap_const_lv6_1);
assign tmp2_fu_534_p2 = (tmp1_fu_528_p2 > ap_const_lv6_38? 1'b1: 1'b0);
assign tmp3_fu_588_p3 = ((tmp2_reg_902)? tmp_51_reg_891: ap_const_lv6_37);
assign tmp4_fu_594_p2 = (tmp3_fu_588_p3 - tmp_51_reg_891);
assign tmp_15_fu_751_p3 = {{tmp_56_fu_747_p1}, {ap_const_lv3_0}};
assign tmp_16_fu_759_p2 = (ap_const_lv5_18 - tmp_15_fu_751_p3);
assign tmp_1_cast_fu_631_p1 = $unsigned(tmp_1_fu_624_p3);
assign tmp_1_fu_624_p3 = {{tmp_53_reg_928}, {ap_const_lv3_0}};
assign tmp_20_cast_fu_765_p1 = $unsigned(tmp_16_fu_759_p2);
assign tmp_2_fu_641_p2 = (ctx_final_bitlen_load_reg_952 > not_fu_635_p2? 1'b1: 1'b0);
assign tmp_3_fu_646_p2 = (ctx_final_bitlen_load_1_reg_972 + ap_const_lv32_1);
assign tmp_4_fu_651_p2 = (tmp_1_cast_reg_958 + ctx_final_bitlen_load_reg_952);
assign tmp_51_fu_524_p1 = ctx_final_datalen_read[5:0];
assign tmp_52_fu_514_p1 = ctx_final_datalen_read[5:0];
assign tmp_53_fu_582_p1 = ctx_final_datalen_read[5:0];
assign tmp_54_fu_655_p1 = tmp_4_fu_651_p2[7:0];
assign tmp_55_fu_689_p1 = ctx_final_bitlen_q1[7:0];
assign tmp_56_fu_747_p1 = i_2_reg_450[1:0];
assign tmp_57_fu_770_p1 = grp_fu_487_p2[7:0];
assign tmp_58_fu_774_p1 = grp_fu_487_p2[7:0];
assign tmp_59_fu_783_p1 = grp_fu_487_p2[7:0];
assign tmp_60_fu_787_p1 = grp_fu_492_p2[7:0];
assign tmp_61_fu_804_p1 = grp_fu_487_p2[7:0];
assign tmp_62_fu_808_p1 = grp_fu_492_p2[7:0];
assign tmp_63_fu_821_p1 = grp_fu_487_p2[7:0];
assign tmp_64_fu_825_p1 = grp_fu_492_p2[7:0];
assign tmp_fu_508_p2 = (ctx_final_datalen_read + ap_const_lv7_1);
assign tmp_s_fu_502_p2 = (ctx_final_datalen_read < ap_const_lv7_38? 1'b1: 1'b0);
always @ (posedge ap_clk)
begin
    ctx_final_bitlen_addr_reg_923 <= 1'b0;
    tmp1_cast_reg_933[6] <= 1'b0;
    tmp_1_cast_reg_958[2:0] <= 3'b000;
    tmp_1_cast_reg_958[31:9] <= 23'b00000000000000000000000;
    ctx_final_bitlen_addr_1_reg_967 <= 1'b1;
    ctx_final_state_addr_reg_1032[2:0] <= 3'b000;
    ctx_final_state_addr_1_reg_1037[2:0] <= 3'b001;
    ctx_final_state_addr_2_reg_1042[2:0] <= 3'b010;
    ctx_final_state_addr_3_reg_1047[2:0] <= 3'b011;
    ctx_final_state_addr_4_reg_1052[2:0] <= 3'b100;
    ctx_final_state_addr_5_reg_1057[2:0] <= 3'b101;
    ctx_final_state_addr_6_reg_1062[2:0] <= 3'b110;
    ctx_final_state_addr_7_reg_1067[2:0] <= 3'b111;
    i_2_cast9_reg_1072[3] <= 1'b0;
    i_2_cast8_reg_1077[4:3] <= 2'b00;
    i_2_cast_reg_1082[31:3] <= 29'b00000000000000000000000000000;
    tmp_20_cast_reg_1095[2:0] <= 3'b000;
    tmp_20_cast_reg_1095[31:5] <= 27'b000000000000000000000000000;
end



endmodule //sha256_final

